### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by lishine** [react-kit/hodux#2]
Congratulations for this lib!
I am the second starrer ))
I want to mention to you that cool lib. And in this issue he mentions automatically wrapping components with babel-plugin.
https://github.com/samdenty/gqless/issues/40

**Comment by chemdemo** [comment]
Will, automatically wrapping components definitely makes import easily, but fundamentally this is still HOC, hooks is more powerful than HoC and i don's like HOC at times.

Using `useStore()` directly does not achieve automatic updates when state changes, so hodux providers `useSelector()` hook with a selector function as parameter, inside useSelector will automatically observe the selected state and update components when any of the selected state changes, it works like `view()` wrapper.

**Comment by lishine** [comment]
It is then not that usefull.
For property of nested object it will not rerender, or if I will want to rerender when any property of the store changes accoring to use like it with view()
