### ISSUE TITLE
疑问：为什么不采用类似mobx的observer/useObserver而是在组件内部调用useSelector

### ISSUE THREAD

**Issue by rainmanhhh** [react-kit/hodux#4]
observer只要把整个组件标记一下就行了，useSelector用到几个属性就要调几次，不会太麻烦吗

**Comment by chemdemo** [comment]
> observer只要把整个组件标记一下就行了，useSelector用到几个属性就要调几次，不会太麻烦吗

有本质的区别，一个是HoC，一个是hook
